### ISSUE TITLE
Brightness function isn't working properly!??! 

### ISSUE THREAD

**Issue by arixank** [wilmouths/RGBLed#4]
WELL IF I USE THE FUNCTION INDIVIDUALLY THEN IT WORKS, BUT WHEN COMBINED WITH OTHER FUNCTION LIKE FLASH, IT DOESN'T WORK AND SIMPLY IGNORES THE BRIGHTNESS AND USES FLASH ONLY!! 
AND I'M USING THEM IN LOOP SECTION SOMEWHAT LIKE THIS :
led. brightness (code) ;
led. flash(code);
And I'm I doing It right?? 

I will attach an image too! ![IMG_20200926_212746.jpg](https://user-images.githubusercontent.com/50585400/94344766-2b0acd80-003f-11eb-8b99-3a833528974b.jpg)

* changed the flash color to cyan but in vain!!

**Comment by wilmouths** [comment]
Hello, thanks for the feedback, I will test and correct this when I have time.

**Comment by wilmouths** [comment]
@arixank Hello,
The Ardunio code being procedural, the instructions are done one after the other, and as the loop function is the main function that "runs in loop", it executes the 2 instructions but so quickly that the brightness is not seen, it will be necessary to put a delay between the two or use the brigthness in the setup function and put a delay before switching to the loop function.

Examples : 
```c++
#include <RGBLed.h>

RGBLed rgb(9, 10, 11, COMMON_CATHODE);

void setup() {}

void loop() {
  rgb.brightness(RGBLed::CYAN, 5);

  delay(1000);
  
  rgb.flash(RGBLed::GREEN, 2500);
}
```

OR

```c++
#include <RGBLed.h>

RGBLed rgb(9, 10, 11, COMMON_CATHODE);

void setup() {
  rgb.brightness(RGBLed::CYAN, 5);

  delay(1000);
}

void loop() { 
  rgb.flash(RGBLed::GREEN, 2500);
}
```

Hoping to have helped you.

**Comment by arixank** [comment]
@wilmouths thanks earlier I had tried with setup one, but will try for the delay to and thanks I didn't knew it worked in that way! 
Will get back soon once it's working! 
Thank you?

**Comment by wilmouths** [comment]
Don't worry, tell me if the method I said works, but given the way arduino works it should work.
