### ISSUE TITLE
 error: 'analogWrite' was not declared in this scope

### ISSUE THREAD

**Issue by Danjuanlab** [wilmouths/RGBLed#8]
error: 'analogWrite' was not declared in this scope

I am using the esp32  board, but this error is prompted when compiling.

**Comment by wilmouths** [comment]
Hello,
sorry for my late answer, I will look on my side with an esp32 if I have the same problem and how to solve it, because it seems to me that an arduino and an esp32 are quite similar on their API.

I'll come back to you.

Regards.

**Comment by calania** [comment]
I have made a pull request that solves it for me. #10
